# WhatATheme
markdown: kramdown

# URL of the Site
url: ""
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl:

# Title of the Site
title: It's me, Jieun!
# Description of the Site
description: A bunch of ideas & projects are scattered here
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: GitHub, DevBlog, Projects
# URL for the Image of custom Favicon
favicon-url:

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: hanjieun9874@gmail.com
facebook_username:
twitter_username:
instagram_username: jieun_kkyu
linkedin_username: jieun-han-53b7621a1
github_username: JieunHan17
youtube_channel_id:
reddit_username:
behance_username:
dribbble_username:
spotify_username:

# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname: thedevslot

# Name of the Author
author-name: Jieun Han
# URL for the Image of the Author
author-image: https://user-images.githubusercontent.com/57990029/122708347-f0188c00-d296-11eb-82de-73d0233769e1.JPG
# 60 Words About the Author
author-about: I am currently in my senior year pursuing a bachelor's degree in computer science at Ajou University, South Korea. I am passionate about both mobile app development and web development. Overall, I am a front end developer, but I don't want to limit myself to just the front end development. I am kind of a person who never stops learning new things and moving forward with my life.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/JieunHan17

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  - scope:
      type: "posts"
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  - scope:
      type: "pages"
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
